module:
  hugoVersion:
    min: "0.84.0"

params:
  ananke_socials:
    - name: github
      url: https://github.com/gabrielbmotta
    - name: linkedin
      url: https://www.linkedin.com/in/gabriel-motta-944281191/
